
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true&useSSL=false
    username: root
    password: root
    platform: mysql
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 7
      connection-timeout: 60000
      maximum-pool-size: 20
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  jackson:
#    serialization:
#      indent-output: true